export const ERROR_CODES = {

    UNAUTHORIZED: "UNAUTHORIZED",
    FORBIDDEN: "FORBIDDEN",

    INVALID_CREDENTIALS: "INVALID_CREDENTIALS",

    USER_NOT_FOUND: "USER_NOT_FOUND",
    HOUSEHOLD_NOT_FOUND: "HOUSEHOLD_NOT_FOUND",
    ITEM_NOT_FOUND: "ITEM_NOT_FOUND",

    VALIDATION_ERROR: "VALIDATION_ERROR",
    INVALID_ACCESS_TOKEN: "INVALID_ACCESS_TOKEN",

    OPERATION_ERROR: "OPERATION_ERROR",
    UNEXPECTED_ERROR: "UNEXPECTED_ERROR",

    USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
    USER_DOES_NOT_EXISTS: "USER_DOES_NOT_EXISTS",

    INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",


} as const

export type ErrorCode = typeof ERROR_CODES[keyof typeof ERROR_CODES];